name = "ChronoMakie"
uuid = "11c6a742-337b-4f20-ab27-6a3fffcce212"
authors = ["Simon Andreas Bjørn <simonabj@ifi.uio.no> and contributors"]
version = "1.0.0-DEV"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
MakieCore = "20f20a25-4f0e-4fdf-b5d1-57303727442b"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
